/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as BlogRouteImport } from './routes/blog/route'
import { Route as AboutRouteImport } from './routes/about/route'
import { Route as BlogPostIdRouteImport } from './routes/blog_/$postId/route'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/dashboard/route.lazy').then((d) => d.Route),
)

const BlogRouteRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/blog/route.lazy').then((d) => d.Route))

const AboutRouteRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about/route.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const BlogPostIdRouteRoute = BlogPostIdRouteImport.update({
  id: '/blog_/$postId',
  path: '/blog/$postId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/blog_/$postId/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRoute
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/blog_/$postId': {
      id: '/blog_/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof BlogPostIdRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRouteRoute
  '/blog': typeof BlogRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/blog/$postId': typeof BlogPostIdRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRouteRoute
  '/blog': typeof BlogRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/blog/$postId': typeof BlogPostIdRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutRouteRoute
  '/blog': typeof BlogRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/blog_/$postId': typeof BlogPostIdRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/blog' | '/dashboard' | '/blog/$postId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/blog' | '/dashboard' | '/blog/$postId'
  id: '__root__' | '/' | '/about' | '/blog' | '/dashboard' | '/blog_/$postId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutRouteRoute: typeof AboutRouteRoute
  BlogRouteRoute: typeof BlogRouteRoute
  DashboardRouteRoute: typeof DashboardRouteRoute
  BlogPostIdRouteRoute: typeof BlogPostIdRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutRouteRoute: AboutRouteRoute,
  BlogRouteRoute: BlogRouteRoute,
  DashboardRouteRoute: DashboardRouteRoute,
  BlogPostIdRouteRoute: BlogPostIdRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/blog",
        "/dashboard",
        "/blog_/$postId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about/route.tsx"
    },
    "/blog": {
      "filePath": "blog/route.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx"
    },
    "/blog_/$postId": {
      "filePath": "blog_/$postId/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
